### ISSUE TITLE
Add Card Display Screen

### ISSUE THREAD

**Issue by lunaticcoding** [lunaticcoding/MilleSandersApp#23]
# TODO's
- [ ] Make Cards iterable in View
- [ ] Make Cards draggable
- [ ] Animate nextCard and prevCard
- [ ] Implement shuffle functionality
- [ ] Implement Filter functionality
