### ISSUE TITLE
Migrate to Clean Architecture

### ISSUE THREAD

**Issue by lunaticcoding** [lunaticcoding/MilleSandersApp#46]
# TODO's
- [ ] Implement BLoC Pattern
- [ ] Use dependency injection for testing
- [ ] Implement Clean Architecture

**Comment by lunaticcoding** [comment]
Paused for now because focus shifted to DDD.
I will finish this once I am done with #47.
